DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(50) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DNI VARCHAR(50) NOT NULL,
FECHA DATE NOT NULL,
ID_DOMICILIO INT NOT NULL);

INSERT INTO DOMICILIOS VALUES(DEFAULT, 'CALLE 54', 10, 'LOCALIDAD 1', 'PROVINCIA 1');
INSERT INTO PACIENTES VALUES(DEFAULT, 'MONTES', 'ANDRES', '1234', '2024-10-25', 1);
